spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hoteldb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  url:
    description: https://cvcbackendhotel.herokuapp.com/hotels/avail/{ID_da_Cidade}
    detail: https://cvcbackendhotel.herokuapp.com/hotels/{ID_Do_Hotel}